parameters:
    astina_translation.loader.class: Astina\Bundle\TranslationBundle\Loader\DoctrineLoader

services:

    astina_translation.loader:
        class: %astina_translation.loader.class%
        arguments: [ "@astina_translation.repository.translation" ]
        tags:
            - { name: translation.loader, alias: db }

    astina_translation.repository.translation:
        class: Astina\Bundle\TranslationBundle\Entity\Translation
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AstinaTranslationBundle:Translation

